name: NPM Publish
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # https://github.com/ReeganExE/checkout
      # 🚀 Lightweight. No pointless progress. A mod version of actions/checkout.
      - uses: reeganexe/checkout@v3

      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Build
        run: npm ci && npm run build

      - name: NPM Publish
        run: |
          npm version ${GITHUB_REF#refs/tags/v} --no-git-tag-version --no-commit-hooks --allow-same-version
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
